# Generated by Django 5.2.6 on 2025-11-27 06:05

import ckeditor.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="city",
        ),
        migrations.AddField(
            model_name="car",
            name="features",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("Air Conditioning", "Air Conditioning"),
                    (
                        "Anti-Lock Braking System (ABS)",
                        "Anti-Lock Braking System (ABS)",
                    ),
                    ("Navigation System", "Navigation System"),
                    ("Power Steering", "Power Steering"),
                    ("Leather Seats", "Leather Seats"),
                    ("Bluetooth Connectivity", "Bluetooth Connectivity"),
                    ("Backup Camera", "Backup Camera"),
                    ("Cruise Control", "Cruise Control"),
                    ("Sunroof/Moonroof", "Sunroof/Moonroof"),
                    ("Alloy Wheels", "Alloy Wheels"),
                    ("Heated Seats", "Heated Seats"),
                    ("Automatic Windows", "Automatic Windows"),
                    ("Keyless Entry", "Keyless Entry"),
                    ("GPS Navigation", "GPS Navigation"),
                    ("Parking Sensors", "Parking Sensors"),
                    ("Electric Mirrors", "Electric Mirrors"),
                    ("Remote Start", "Remote Start"),
                    ("Blind Spot Detection", "Blind Spot Detection"),
                    ("Lane Departure Warning", "Lane Departure Warning"),
                    ("LED Headlights", "LED Headlights"),
                    ("Rain Sensing Wipers", "Rain Sensing Wipers"),
                    ("Multi-Function Steering Wheel", "Multi-Function Steering Wheel"),
                    ("Onboard Computer", "Onboard Computer"),
                    ("Traction Control", "Traction Control"),
                    (
                        "Tire Pressure Monitoring System (TPMS)",
                        "Tire Pressure Monitoring System (TPMS)",
                    ),
                    ("Auto-Dimming Rearview Mirror", "Auto-Dimming Rearview Mirror"),
                    ("Heated Steering Wheel", "Heated Steering Wheel"),
                    ("Seat Memory", "Seat Memory"),
                    ("Front Fog Lights", "Front Fog Lights"),
                    ("Other", "Other"),
                ],
                max_length=550,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.CharField(max_length=100),
        ),
    ]
